version: '3.7'
services:

  # Main Redis Service
  monorail-redis:
    image: redis:6.2.6-alpine
    container_name: monorail-redis
    restart: unless-stopped
    command: [sh, -c, "redis-server /etc/main.conf"]
    ports:
      - "6379:6379"
    environment:
      SERVICE_NAME: monorail-redis
      SERVICE_TAGS: development
    volumes:
      - ./configurations/redis/main.conf:/etc/main.conf
    networks:
      monorail-network:
        aliases:
          - redis-main

  # Postgres Write Service
  monorail-db:
    image: postgres:14.1-alpine3.15
    container_name: monorail-db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "monorail"
      POSTGRES_USER: "monorail_admin"
      POSTGRES_PASSWORD: "local_dev"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      SERVICE_NAME: monorail-db
      SERVICE_TAGS: development
    volumes:
      - monorail-db-data:/var/lib/postgresql/data
    networks:
      monorail-network:
        aliases:
          - database

  #PHP Web Service
  monorail-app:
    image: monorail-app:latest
    container_name: monorail-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: monorail-app
      SERVICE_TAGS: development
    working_dir: /var/www
    volumes:
      - ../monorail:/var/www
      - ./configurations/php/docker-php-ext-phpredis.ini:/usr/local/etc/php/conf.d/docker-php-ext-phpredis.ini
    networks:
      monorail-network:
        aliases:
          - app
    depends_on:
      - monorail-redis
      - monorail-webserver
      - monorail-db

  #Nginx Service
  monorail-webserver:
    image: nginx:1.21.4-alpine
    container_name: monorail-webserver
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_SERVER_NAME=local.monorail.test
      - NGINX_SSL_CRT_FILE_NAME=local.monorail.test.crt
      - NGINX_SSL_KEY_FILE_NAME=local.monorail.test.key
    entrypoint: /var/run/entrypoint.sh
    volumes:
      - ./configurations/nginx/entrypoint.sh:/var/run/entrypoint.sh:rw
      - ../monorail:/var/www
      - ./configurations/nginx/conf.d/:/etc/nginx/conf.d/
      - ./configurations/nginx/ssl_keys/:/etc/nginx/ssl/
    networks:
      monorail-network:
        aliases:
          - web

#Docker Networks
networks:
  monorail-network:

#Volumes
volumes:
  monorail-db-data:
    driver: local
