FROM nginx:1.21.4-alpine

ARG DOMAIN

RUN apk update \
    && apk add --no-cache openssl

COPY default.conf.template /etc/nginx/conf.d/default.conf
RUN sed -i "s/<SERVER_NAME>/${DOMAIN}/g" /etc/nginx/conf.d/default.conf

COPY options-ssl-nginx.conf /etc/nginx/
COPY hsts.conf /etc/nginx/
COPY nginx_production.sh /customization/nginx.sh

RUN chmod +x /customization/nginx.sh

EXPOSE 80

CMD ["/customization/nginx.sh"]